// logger/config.js
//
// Loads contract addresses and ABIs for use by blockchain-logger.js.
//
// Resolution order for contract addresses:
//   1. Environment variables (set as GitHub Actions Secrets in CI)
//   2. deployments/<network>.json written by deploy.js
//   3. Hard error — deployment info is required to proceed
//
// ABIs are loaded from the Hardhat artifacts/ directory, which is
// generated by `npx hardhat compile`. In GitHub Actions the compile
// step runs before the logger, so artifacts are always fresh.

const fs   = require("fs");
const path = require("path");

// ─── Network ──────────────────────────────────────────────────────────────────

/**
 * The Ethereum network name the logger targets.
 * Defaults to "sepolia" — override via NETWORK env var for local testing.
 */
const NETWORK = process.env.NETWORK || "sepolia";

// ─── Contract addresses ───────────────────────────────────────────────────────

/**
 * Load contract addresses.
 * GitHub Actions Secrets take priority over the deployments JSON file.
 */
function loadAddresses() {
  // Try environment variables first (GitHub Actions Secrets)
  const fromEnv = {
    pipelineRegistry: process.env.PIPELINE_REGISTRY_ADDRESS,
    eventLogger:      process.env.EVENT_LOGGER_ADDRESS,
    verifier:         process.env.VERIFIER_ADDRESS,
  };

  if (
    fromEnv.pipelineRegistry &&
    fromEnv.eventLogger &&
    fromEnv.verifier
  ) {
    return fromEnv;
  }

  // Fall back to deployments/<network>.json
  const deploymentsPath = path.resolve(
    __dirname,
    `../deployments/${NETWORK}.json`
  );

  if (!fs.existsSync(deploymentsPath)) {
    throw new Error(
      `config.js: no deployment info found.\n` +
      `  Expected: ${deploymentsPath}\n` +
      `  Run: npx hardhat run scripts/deploy.js --network ${NETWORK}`
    );
  }

  const deployment = JSON.parse(fs.readFileSync(deploymentsPath, "utf8"));

  return {
    pipelineRegistry: deployment.pipelineRegistryAddress,
    eventLogger:      deployment.eventLoggerAddress,
    verifier:         deployment.verifierAddress,
  };
}

// ─── ABI loader ───────────────────────────────────────────────────────────────

/**
 * Load a contract's ABI from the Hardhat artifacts directory.
 *
 * @param   {string} contractName  e.g. "PipelineRegistry"
 * @returns {Array}                The ABI array.
 */
function loadAbi(contractName) {
  const artifactPath = path.resolve(
    __dirname,
    `../artifacts/contracts/${contractName}.sol/${contractName}.json`
  );

  if (!fs.existsSync(artifactPath)) {
    throw new Error(
      `config.js: ABI not found for ${contractName}.\n` +
      `  Expected: ${artifactPath}\n` +
      `  Run: npx hardhat compile`
    );
  }

  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  return artifact.abi;
}

// ─── Pipeline ID ──────────────────────────────────────────────────────────────

/**
 * The pipelineId registered in PipelineRegistry.
 * Set via PIPELINE_ID env var / GitHub Actions Secret.
 * Defaults to 1 (the first registered pipeline).
 */
const PIPELINE_ID = parseInt(process.env.PIPELINE_ID || "1", 10);

// ─── RPC endpoint ─────────────────────────────────────────────────────────────

/**
 * The JSON-RPC URL for the target network.
 * Must be set as a GitHub Actions Secret: SEPOLIA_RPC_URL
 */
const RPC_URL = process.env.SEPOLIA_RPC_URL || "";
if (!RPC_URL) {
  throw new Error(
    "config.js: SEPOLIA_RPC_URL is not set.\n" +
    "  Add it as a GitHub Actions Secret or in your .env file."
  );
}

// ─── Bot wallet private key ───────────────────────────────────────────────────

/**
 * Private key of the GitHub Actions bot wallet.
 * Must be set as a GitHub Actions Secret: BOT_PRIVATE_KEY
 * This wallet must be authorised in both EventLogger and Verifier.
 */
const BOT_PRIVATE_KEY = process.env.BOT_PRIVATE_KEY || "";
if (!BOT_PRIVATE_KEY) {
  throw new Error(
    "config.js: BOT_PRIVATE_KEY is not set.\n" +
    "  Add it as a GitHub Actions Secret."
  );
}

// ─── Assembled config ─────────────────────────────────────────────────────────

const addresses = loadAddresses();

const CONFIG = {
  network:        NETWORK,
  rpcUrl:         RPC_URL,
  botPrivateKey:  BOT_PRIVATE_KEY,
  pipelineId:     PIPELINE_ID,

  addresses: {
    pipelineRegistry: addresses.pipelineRegistry,
    eventLogger:      addresses.eventLogger,
    verifier:         addresses.verifier,
  },

  abis: {
    pipelineRegistry: loadAbi("PipelineRegistry"),
    eventLogger:      loadAbi("EventLogger"),
    verifier:         loadAbi("Verifier"),
  },
};

module.exports = CONFIG;
const addresses = loadAddresses();

const CONFIG = {
  network:       NETWORK,
  rpcUrl:        RPC_URL,
  botPrivateKey: BOT_PRIVATE_KEY,
  pipelineId:    PIPELINE_ID,

  addresses: {
    pipelineRegistry: addresses.pipelineRegistry,
    eventLogger:      addresses.eventLogger,
    verifier:         addresses.verifier,
  },

  // ABIs loaded lazily so missing artifacts don't crash on import
  get abis() {
    return {
      pipelineRegistry: loadAbi("PipelineRegistry"),
      eventLogger:      loadAbi("EventLogger"),
      verifier:         loadAbi("Verifier"),
    };
  },
};

module.exports = CONFIG;
